import { useState } from 'react';
import type { Option } from '../types/market';
import { optionCost, breakEven, payoff, riskMetrics } from '../utils/optionsMath';
import { money } from '../utils/format';

export function OptionChain({options,selected,budget,price,onSelect}:{options:Option[];selected:Option;budget:number;price:number;onSelect:(ticker:string)=>void}) {
 const [query,setQuery]=useState(''),[sort,setSort]=useState('strike'),[showAll,setShowAll]=useState(false),[page,setPage]=useState(0);
 const filtered=options.filter(o=>(showAll||optionCost(o)<=budget)&&o.ticker.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='premium'?optionCost(a)-optionCost(b):sort==='trades'?(b.trades||0)-(a.trades||0):a.strike-b.strike);
 const pages=Math.max(1,Math.ceil(filtered.length/8)),current=Math.min(page,pages-1);
 return <section className="option-chain" aria-label="Escolher uma opção"><h2>Qual opção você quer simular?</h2><p>Mesmo papel, direção e prazo; preços e pontos de equilíbrio diferentes. Compare e escolha.</p><p><b>Selecionada: {selected.ticker}</b> · strike {money(selected.strike)} · custo {money(optionCost(selected))}</p>
 <div className="chain-controls"><label>Buscar código<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Ex.: PETR…"/></label><label>Ordenar por<select value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="strike">Preço de referência</option><option value="premium">Menor custo</option><option value="trades">Mais negócios no pregão</option></select></label></div>
 <label><input type="checkbox" checked={showAll} onChange={e=>{setShowAll(e.target.checked);setPage(0);}}/> Mostrar também as que não cabem no limite</label>
 <p className="disclaimer">{filtered.length} séries nesta lista. Cenário comparado: ação a {money(price)} no vencimento. Último negócio não garante que você consiga comprar por esse preço.</p>
 <div className="chain-list">{filtered.slice(current*8,current*8+8).map(o=>{const cost=optionCost(o),r=payoff(o,price),m=riskMetrics(o,price),disabled=cost>budget;return <label key={o.ticker} className={`chain-card ${selected.ticker===o.ticker?'selected':''} ${disabled?'unaffordable':''}`}><div><input type="radio" name="option-series" checked={selected.ticker===o.ticker} disabled={disabled} onChange={()=>onSelect(o.ticker)}/><b>{o.ticker}</b> · {o.type==='CALL'?'Alta':'Queda'}</div><dl><div><dt>Preço de referência (strike)</dt><dd>{money(o.strike)}</dd></div><div><dt>Último prêmio / unidade</dt><dd>{money(o.premium/o.quoteFactor)}</dd></div><div><dt>Custo · 100 unidades</dt><dd>{money(cost)}</dd></div><div><dt>Começa a lucrar com ação {o.type==='CALL'?'acima de':'abaixo de'}</dt><dd>{money(breakEven(o))}</dd></div><div><dt>Neste cenário</dt><dd>Resultado {money(r.result)} ({m.multiple.toLocaleString('pt-BR',{maximumFractionDigits:2})}×)</dd></div></dl><small>{o.trades} negócios no pregão · não mede liquidez atual</small>{disabled&&<p>Faltam {money(cost-budget)} no limite para esta série.</p>}</label>})}</div>
 {!filtered.length&&<p>Nenhuma série com esse filtro.</p>}<div className="simple-presets"><button disabled={current===0} onClick={()=>setPage(current-1)}>Anterior</button><span>Página {current+1} de {pages}</span><button disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Próxima</button></div><p className="disclaimer">Seleção inicial: strike mais próximo da ação entre as opções que cabem. Não é recomendação. × = resultado líquido do prêmio ÷ custo, antes de taxas e tributos; não é chance de ganhar.</p></section>;
}
