import { test } from 'node:test';
import assert from 'node:assert/strict';
import { payoff, optionCost, breakEven, riskMetrics } from './optionsMath.ts';
import { parseCotahist } from './cotahist.ts';
import { selectOptions, availableExpiries } from './optionFilters.ts';
import { journeyAvailability, safeJourneyStep } from './journey.ts';
import type { Option } from '../types/market.ts';
const call:Option={ticker:'TEST',underlying:'TEST4',type:'CALL',strike:32,premium:.42,contractSize:100,quoteFactor:1,expiry:'2026-10-16',sourceDate:'2026-09-30',sourceUrl:'https://example.com',dataType:'illustrative',premiumType:'illustrative',quantityType:'illustrative',style:'test',specificationDate:'2026-09-30'};
test('múltiplo é lucro líquido / prêmio, não valor bruto nem probabilidade',()=>{const o={...call,premium:.3};assert.equal(riskMetrics(o,33.2).multiple,3);assert.equal(riskMetrics(o,32.9).multiple,2);assert.equal(riskMetrics(o,0).multiple,-1);assert.equal(riskMetrics(o,32.3).multiple,0);assert.equal(riskMetrics(o,33).maxProfit,null);assert.equal(riskMetrics({...o,type:'PUT'},30).maxProfit,3170);});
function row(ticker:string,market:string,overrides:Record<number,string>={}){const r=Array(245).fill(' ');const fields:Record<number,string>={0:'01',2:'20261002',12:ticker.padEnd(12),24:market,39:'PN        ',52:'R$  ',108:'0000000000030',147:'00012',170:'000000000000003000',188:'0000000003200',201:'0',202:'20261016',210:'0000001',230:'BRTESTACNPR1',...overrides};for(const [p,v] of Object.entries(fields))for(let i=0;i<v.length;i++)r[Number(p)+i]=v[i];return r.join('');}
function file(rows:string[]){return ['00COTAHIST'.padEnd(245),...rows,('99COTAHIST'.padEnd(31)+String(rows.length).padStart(11,'0')).padEnd(245)].join('\n');}
const parse=(rows:string[])=>parseCotahist(file([row('TEST4','010',{108:'0000000003200'}),...rows]),['TEST4'],'2026-10-05','https://example.com');
test('COTAHIST decodifica CALL, PUT, prêmio, strike, vencimento e negócios',()=>{const d=parse([row('TESTJ32','070'),row('TESTV32','080')]);assert.equal(d.stocks[0].price,32);assert.equal(d.options[0].premium,.3);assert.equal(d.options[0].strike,32);assert.equal(d.options[0].expiry,'2026-10-16');assert.equal(d.options[0].trades,12);assert.deepEqual(d.options.map(o=>o.type),['CALL','PUT']);});
test('COTAHIST não confunde classe da ação, ISIN, exercício ou série vencida',()=>{const d=parse([row('GOOD','070'),row('WRONGCLASS','070',{39:'ON        '}),row('WRONGISIN','070',{230:'BROTHERACNPR'}),row('EXERCISE','012'),row('EXPIRED','080',{202:'20261002'}),row('FACTOR','070',{210:'0000100'}),row('ZERO','070',{108:'0000000000000'})]);assert.deepEqual(d.options.map(o=>o.ticker),['GOOD']);assert.deepEqual(d.metadata.excluded,{expired:1,unsupported:1,noPrice:1});});
test('COTAHIST rejeita duplicatas, truncamento, datas futuras e arquivo sem séries',()=>{assert.throws(()=>parse([row('DUP','070'),row('DUP','070')]));assert.throws(()=>parse([row('BAD','070').slice(0,-1)]));assert.throws(()=>parse([row('FUTURE','070',{2:'20261006'})]));assert.throws(()=>parse([]));assert.throws(()=>parseCotahist('00COTAHIST',[], '2026-10-05',''));});
test('CALL: perda total, equilíbrio e ganho no vencimento',()=>{assert.equal(optionCost(call),42);assert.equal(payoff(call,0).result,-42);assert.equal(payoff(call,32).result,-42);assert.equal(payoff(call,32.42).result,0);assert.equal(payoff(call,38).result,558);assert.equal(breakEven(call),32.42);});
test('PUT: perda limitada ao prêmio, equilíbrio e ganho',()=>{const put={...call,type:'PUT' as const};assert.equal(payoff(put,38).result,-42);assert.equal(payoff(put,31.58).result,0);assert.equal(payoff(put,28).result,358);assert.equal(payoff(put,0).result,3158);assert.equal(breakEven(put),31.58);});
test('fator de cotação e quantidade não são confundidos',()=>{assert.equal(optionCost({...call,quoteFactor:100}),.42);assert.equal(payoff({...call,quoteFactor:100},33).result,99.58);});
test('filtros: direção, vencimento, ativo, orçamento, dados inválidos e strike mais próximo',()=>{const data=[call,{...call,ticker:'NEAR',strike:30,premium:.5},{...call,ticker:'PUT',type:'PUT' as const},{...call,ticker:'OTHER',underlying:'OTHER4'},{...call,ticker:'DATE',expiry:'2026-12-18'},{...call,ticker:'BAD',premium:NaN}];assert.deepEqual(selectOptions(data,'TEST4','CALL','2026-10-16',50,30).affordable.map(x=>x.ticker),['NEAR','TEST']);assert.equal(selectOptions(data,'TEST4','CALL','2026-10-16',20,30).minimum,42);assert.equal(selectOptions(data,'TEST4','CALL','2026-10-16',-1,30).affordable.length,0);assert.equal(selectOptions(data,'UNKNOWN','CALL','2026-10-16',50,30).minimum,null);assert.deepEqual(availableExpiries(data,'TEST4','PUT'),['2026-10-16']);});
test('preço negativo ou não finito é rejeitado',()=>{assert.throws(()=>payoff(call,-1));assert.throws(()=>payoff(call,NaN));});
test('comparação de orçamento: mais limite não multiplica a posição',()=>{const low=selectOptions([call],'TEST4','CALL',call.expiry,50,32).affordable[0];const high=selectOptions([call],'TEST4','CALL',call.expiry,100,32).affordable[0];assert.equal(low.ticker,high.ticker);assert.equal(payoff(low,35).result,payoff(high,35).result);assert.equal(100-optionCost(high),58);assert.equal(selectOptions([call],'TEST4','CALL',call.expiry,25,32).affordable.length,0);});
test('comparação de prazo mantém as séries separadas, sem inventar preços',()=>{const later={...call,ticker:'LATER',expiry:'2026-12-18',premium:1.2};assert.equal(selectOptions([call,later],'TEST4','CALL',later.expiry,100,32).affordable.length,0);assert.equal(selectOptions([call,later],'TEST4','CALL',later.expiry,150,32).affordable[0].ticker,'LATER');assert.equal(selectOptions([call,later],'TEST4','PUT',later.expiry,150,32).minimum,null);});
test('jornada bloqueia CALL de 120 para orçamento de 100 sem bloquear PUT acessível',()=>{const data=[{...call,premium:1.2},{...call,type:'PUT' as const,premium:.42}];const a=journeyAvailability(data,'TEST4',100,call.expiry);assert.equal(a.canContinue,true);assert.equal(a.directions[0].enabled,false);assert.equal(a.directions[0].minimum,120);assert.equal(a.directions[1].enabled,true);assert.equal(journeyAvailability(data,'TEST4',120,call.expiry).directions[0].enabled,true);});
test('jornada bloqueia prazo caro, orçamento inválido e direção sem série',()=>{const data=[call,{...call,expiry:'2026-12-18',premium:1.2}];const a=journeyAvailability(data,'TEST4',100,'2026-12-18');assert.equal(a.canContinue,false);assert.equal(a.dates[0].enabled,true);assert.equal(a.dates[1].enabled,false);assert.equal(a.directions[1].minimum,null);for(const b of [0,-1,NaN,Infinity,1000001])assert.equal(journeyAvailability(data,'TEST4',b,call.expiry).canContinue,false);});
test('links diretos e rascunhos não avançam com seleção ou motivo inválido',()=>{assert.equal(safeJourneyStep(5,false,false,false),1);assert.equal(safeJourneyStep(4,true,false,true),2);assert.equal(safeJourneyStep(5,true,true,false),3);assert.equal(safeJourneyStep(5,true,true,true),5);assert.equal(safeJourneyStep(0,false,false,false),0);});
test('CALL: estar dentro do dinheiro ainda pode significar perda parcial',()=>{const p=payoff(call,32.21);assert.equal(p.value,21);assert.equal(p.cost,42);assert.equal(p.result,-21);});
test('PUT: as faixas de lucro e prejuízo invertem o sentido do preço',()=>{const put={...call,type:'PUT' as const};assert.equal(payoff(put,32).result,-42);assert.equal(payoff(put,31.79).result,-21);assert.equal(payoff(put,31.58).result,0);assert.ok(payoff(put,31.57).result>0);assert.equal(payoff(put,33).value,0);});
test('limites da CALL distinguem strike e equilíbrio em centavos',()=>{assert.equal(payoff(call,32).value,0);assert.equal(payoff(call,32.01).result,-41);assert.equal(payoff(call,32.41).result,-1);assert.equal(payoff(call,32.42).result,0);assert.equal(payoff(call,32.43).result,1);});
