import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowDownRight, ArrowLeft, ArrowUpRight, BookOpen, Check, ChevronRight, CircleHelp, Eye, Gauge, Info, LockKeyhole, Search, Sparkles } from 'lucide-react';
import { flushSync } from 'react-dom';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { BottomSheet } from './components/BottomSheet';
import { ResultExplanation, PriceRanges, OptionGuide, TermStrikeGuide } from './components/ResultDiscovery';
import stockData from './data/stocks.json';
import optionData from './data/options.json';
import type { Stock, Option, Direction, Simulation } from './types/market';
import { optionCost, payoff, breakEven } from './utils/optionsMath';
import { availableExpiries, selectOptions, validOption } from './utils/optionFilters';
import { money, date, shortDate, daysFrom } from './utils/format';

const stocks = stockData as Stock[];
const options = optionData as Option[];
const KEY = 'xp-pulse-v2';
const steps = ['stock','context','reason','terms','slip','option','simulator','review','created','pulse','replay','learned'] as const;
type Step = typeof steps[number];
type State = { step:Step; ticker:string; direction:Direction; reason:string; customReason:string; expiry:string; budget:string; selected:string; finalPrice:number; lesson:number; saved:Simulation[]; activeId:string; concepts:string[]; quizPassed:boolean };
const initial: State = {step:'stock',ticker:'PETR4',direction:'up',reason:'',customReason:'',expiry:'2026-10-16',budget:'50',selected:'',finalPrice:48.72,lesson:0,saved:[],activeId:'',concepts:[],quizPassed:false};
const definitions:Record<string,string> = {
  CALL:'Direito de comprar o ativo pelo preço de exercício, conforme o contrato. A alta precisa ser suficiente para compensar o prêmio no vencimento.',
  PUT:'Direito de vender o ativo pelo preço de exercício, conforme o contrato. A queda precisa ser suficiente para compensar o prêmio no vencimento.',
  STRIKE:'Preço de exercício definido na série. É usado para calcular seu valor intrínseco no vencimento.',
  PRÊMIO:'Preço pago pela opção. O custo da posição usa esse preço, a quantidade e o fator de cotação.',
  VENCIMENTO:'Data em que a opção chega ao fim. No exercício, podem existir obrigações de entrega ou recursos adicionais.',
  PAYOFF:'Resultado simplificado no vencimento: valor intrínseco da posição menos o custo do prêmio. Custos e tributos não estão incluídos.',
  'BREAK-EVEN':'Preço do ativo em que o resultado simplificado no vencimento é zero: strike mais prêmio por unidade na CALL; strike menos prêmio por unidade na PUT.',
  TEMPO:'Uma opção tem tempo limitado. Mantidas as demais condições, a passagem do tempo tende a reduzir seu valor temporal. Isso não é uma previsão de preço.',
  VOLATILIDADE:'Expressa a intensidade das oscilações esperadas ou observadas. Será um próximo módulo.',
  THETA:'Medida de sensibilidade do preço da opção à passagem do tempo, mantendo outras condições constantes. Será um próximo módulo.'
};

function restore():State {
  try {
    const raw = JSON.parse(localStorage.getItem(KEY)||'null');
    if (!raw || !stocks.some(s=>s.ticker===raw.ticker) || !steps.includes(raw.step)) return initial;
    const saved = Array.isArray(raw.saved) ? raw.saved.filter((s:Simulation)=>s && typeof s.id==='string' && s.stock && stocks.some(a=>a.ticker===s.stock.ticker) && s.option && validOption(s.option) && Number.isFinite(s.finalPrice) && s.finalPrice>=0 && Number.isFinite(s.budget) && typeof s.reason==='string' && Number.isFinite(Date.parse(s.createdAt))).slice(0,100) : [];
    const concepts = Array.isArray(raw.concepts) ? raw.concepts.filter((c:unknown)=>typeof c==='string' && c in definitions) : [];
    return {...initial,step:raw.step,ticker:raw.ticker,direction:raw.direction==='down'?'down':'up',reason:typeof raw.reason==='string'?raw.reason.slice(0,240):'',customReason:typeof raw.customReason==='string'?raw.customReason.slice(0,240):'',expiry:typeof raw.expiry==='string'?raw.expiry:initial.expiry,budget:typeof raw.budget==='string'?raw.budget:'50',selected:typeof raw.selected==='string'?raw.selected:'',finalPrice:Number.isFinite(raw.finalPrice)&&raw.finalPrice>=0?raw.finalPrice:48.72,lesson:Number.isInteger(raw.lesson)?Math.min(2,Math.max(0,raw.lesson)):0,saved,activeId:saved.some((s:Simulation)=>s.id===raw.activeId)?raw.activeId:saved[0]?.id||'',concepts:[...new Set(concepts)] as string[],quizPassed:raw.quizPassed===true};
  } catch { return initial; }
}

function Primary({children,onClick,disabled=false}:{children:ReactNode;onClick:()=>void;disabled?:boolean}) { return <button className="xp-primary" onClick={onClick} disabled={disabled}>{children}</button>; }
function Choices({value,onChange,items,label,className='choice-list'}:{value:string;onChange:(v:string)=>void;items:{value:string;label:ReactNode}[];label:string;className?:string}){
  return <RadioGroup aria-label={label} value={value} onValueChange={onChange} className={className}>{items.map((item,i)=><label className={`choice ${value===item.value?'selected':''}`} key={item.value}><RadioGroupItem value={item.value} id={`${label}-${i}`}/><span>{item.label}</span></label>)}</RadioGroup>;
}

export default function App(){
  const [state,setState] = useState<State>(restore);
  const [query,setQuery] = useState('');
  const [uncertain,setUncertain] = useState(false);
  const [storageError,setStorageError] = useState(false);
  const [quiz,setQuiz] = useState('');
  const [quizFeedback,setQuizFeedback] = useState('');
  const [timeDays,setTimeDays] = useState(20);
  const headingRef = useRef<HTMLElement>(null);
  const current = useRef(state); current.current=state;
  const patch=(partial:Partial<State>)=>setState(s=>({...s,...partial}));
  const go=(step:Step,partial:Partial<State>={})=>{
    setState(s=>({...s,...partial,step}));
    window.history.pushState({pulseStep:step},'',`#${step}`);
  };
  const stock=stocks.find(s=>s.ticker===state.ticker)!;
  const type=state.direction==='up'?'CALL':'PUT';
  const expiries=availableExpiries(options,stock.ticker,type);
  const expiry=expiries.includes(state.expiry)?state.expiry:expiries[0]||'';
  const budget=Number(state.budget.replace(',','.'));
  const budgetValid=state.budget.trim()!=='' && Number.isFinite(budget) && budget>0 && budget<=1000000;
  const selection=selectOptions(options,stock.ticker,type,expiry,budget,stock.price);
  const option=selection.affordable.find(o=>o.ticker===state.selected)||selection.affordable[0];
  const active=state.saved.find(s=>s.id===state.activeId)||state.saved[0];
  const reason=state.reason==='Outro motivo'?state.customReason.trim():state.reason;
  const cost=option?optionCost(option):0;
  const be=option?breakEven(option):0;
  const score=state.concepts.length*10+(state.quizPassed?30:0);
  const sequence:Step[]=['stock','context','reason','terms','slip','option','simulator','review'];
  const stepIndex=sequence.indexOf(state.step);
  const learn=(...concepts:string[])=>setState(s=>({...s,concepts:[...new Set([...s.concepts,...concepts])]}));
  const chooseStock=(ticker:string)=>{ const selected=stocks.find(s=>s.ticker===ticker); if(!selected)throw new Error('Empresa indisponível'); go('context',{ticker,reason:'',customReason:'',selected:'',finalPrice:selected.price,lesson:0});setUncertain(false); };
  const back=()=>{
    if(state.step==='option'&&state.lesson>0){patch({lesson:state.lesson-1});return;}
    const target=stepIndex>0?sequence[stepIndex-1]:['replay','created','learned'].includes(state.step)?'pulse':'stock';
    go(target);
  };
  useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(state));setStorageError(false);}catch{setStorageError(true);}},[state]);
  useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});headingRef.current?.focus({preventScroll:true});},[state.step,state.lesson]);
  useEffect(()=>{
    window.history.replaceState({pulseStep:current.current.step},'',`#${current.current.step}`);
    const pop=()=>{const target=location.hash.slice(1);if(steps.includes(target as Step))setState(s=>({...s,step:target as Step}));};
    window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);
  },[]);
  useEffect(()=>{
    type Tool = {name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
    const ctx=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!ctx?.registerTool)return;
    const lifecycle=new AbortController();
    try{void Promise.resolve(ctx.registerTool({name:'start_xp_pulse_simulation',description:'Escolhe uma empresa e abre o contexto educacional. Não cria nem salva uma tese.',inputSchema:{type:'object',properties:{ticker:{type:'string',enum:stocks.map(s=>s.ticker)}},required:['ticker'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||!('ticker' in input)||Object.keys(input).length!==1||typeof input.ticker!=='string'||!stocks.some(s=>s.ticker===input.ticker))throw new Error('Informe um ticker válido da base.');flushSync(()=>chooseStock(input.ticker as string));return {ticker:current.current.ticker,step:current.current.step};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[]);
  const save=()=>{
    if(!option||!reason||!budgetValid)return;
    const simulation:Simulation={id:crypto.randomUUID(),stock:{...stock},option:{...option},direction:state.direction,reason,budget,finalPrice:state.finalPrice,createdAt:new Date().toISOString()};
    go('created',{saved:[simulation,...state.saved].slice(0,100),activeId:simulation.id});
  };
  const reasonChoices=[...(state.direction==='up'?stock.bull:stock.bear).map(f=>f.title),'Outro motivo','Só quero experimentar'];
  const topDate=state.step==='stock'?'Snapshot fixo • datas em cada empresa':`Ação: ${date(stock.sourceDate)}${option&&['option','simulator','review'].includes(state.step)?` · prêmio: ${date(option.sourceDate)}`:''}`;
  const stockView=<><div className="eyebrow">COMECE POR UMA EMPRESA</div><h1>Qual empresa está<br/>no seu radar hoje?</h1><p className="lead">Escolha uma empresa que você conhece.<br className="desktop-break"/> A parte técnica vem depois.</p><label className="search"><Search size={19}/><input aria-label="Buscar ticker ou empresa" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ticker ou empresa"/></label><div className="stock-grid">{stocks.filter(s=>`${s.ticker} ${s.name}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).map(s=><button key={s.ticker} onClick={()=>chooseStock(s.ticker)} className="stock-card"><div><b>{s.ticker}</b><span>{s.name}</span><small>{date(s.sourceDate)}</small></div><div className="stock-price"><strong>{money(s.price)}</strong><span>fechamento</span></div><ChevronRight size={19}/></button>)}</div>{!stocks.some(s=>`${s.ticker} ${s.name}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')))&&<p role="status" className="lead">Nenhuma empresa encontrada. A base contém Petrobras, Vale, Itaú e B3.</p>}<div className="intro-note"><BookOpen size={20}/><p>Uma ideia. Quatro decisões.<br/><b>Aprenda testando os cenários.</b></p></div>{state.saved.length>0&&<button className="secondary-button" onClick={()=>go('pulse')}>Abrir Meu Pulse · {state.saved.length} tese(s)</button>}</>;
  const noOption=<div className="empty-option"><CircleHelp className="empty-icon"/><h1>{selection.minimum===null?'Sem série nesta base.':'Este valor não cobre a posição.'}</h1><p>{selection.minimum===null?'Não há série válida para essa combinação de empresa, direção e vencimento.':<>Com {money(budget)}, nenhuma das séries desta base cabe na posição didática de 100 unidades. O menor custo é <b>{money(selection.minimum)}</b>.</>}</p><p>Seu valor permanece como você escolheu.</p><Primary onClick={()=>go('terms')}>Ajustar valor ou vencimento</Primary><button className="secondary-button" onClick={()=>go('context')}>Revisar minha visão</button></div>;
  return <main><div className="ambient"/><div className="app-shell">
    <header className="xp-header"><div className="flex items-center gap-3">{state.step!=='stock'&&<button className="icon-button" onClick={back} aria-label="Voltar"><ArrowLeft size={20}/></button>}<div className="logo"><span>XP</span><b>PULSE</b></div></div><button className="score" onClick={()=>state.saved.length?go('learned'):undefined} aria-label={`${score} pontos de progresso educacional`}><Sparkles size={15}/>{score} Pulse</button></header>
    <Progress className="progress-track" value={stepIndex>=0?(stepIndex+1)/sequence.length*100:100} aria-label="Progresso da jornada"/>
    <div className="simulation-banner"><LockKeyhole size={13}/><span>Simulação educacional · nenhum dinheiro real</span></div>
    {storageError&&<p className="storage-warning" role="alert">O navegador não permitiu salvar. Esta sessão funciona, mas pode ser perdida ao fechar a página.</p>}
    <section className="screen" tabIndex={-1} ref={headingRef} aria-label="Jornada XP Pulse" key={state.step}>
      {state.step==='stock'&&stockView}
      {state.step==='context'&&<><div className="stock-title"><div><span>{stock.ticker}</span><b>{stock.name}</b></div><strong>{money(stock.price)}</strong></div><h1>O que pode mexer<br/>com essa ação?</h1><p className="lead">São fatores para entender o negócio. A ação responde a várias influências ao mesmo tempo.</p>{(['up','down'] as const).map(tone=><div className="factor-group" key={tone}><div className={`factor-heading ${tone}`}>{tone==='up'?<ArrowUpRight/>:<ArrowDownRight/>}PODE FAVORECER {tone==='up'?'ALTA':'QUEDA'}</div>{(tone==='up'?stock.bull:stock.bear).map(f=><div className="factor-card" key={f.title}><span>{f.icon}</span><div><b>{f.title}</b><p>{f.short}</p><BottomSheet label="Entender melhor" title={f.title} description={f.detail}/></div></div>)}</div>)}<div className="decision-box"><h2>Agora, qual é sua visão?</h2><div className="direction-grid"><button onClick={()=>go('reason',{direction:'up',reason:'',selected:''})}><ArrowUpRight/><span><b>Acredito em alta</b><small>A ação pode subir</small></span></button><button onClick={()=>go('reason',{direction:'down',reason:'',selected:''})}><ArrowDownRight/><span><b>Acredito em queda</b><small>A ação pode cair</small></span></button></div><button className="unsure" onClick={()=>setUncertain(!uncertain)} aria-expanded={uncertain}><CircleHelp size={17}/>Ainda não sei</button>{uncertain&&<div className="uncertain" role="status"><p>Tudo bem. Explore os fatores ou escolha uma direção apenas para experimentar. Não é uma previsão sua.</p><button className="secondary-button" onClick={()=>go('terms',{direction:'up',reason:'Só quero experimentar',selected:''})}>Experimentar um cenário de alta</button><button className="secondary-button" onClick={()=>go('terms',{direction:'down',reason:'Só quero experimentar',selected:''})}>Experimentar um cenário de queda</button></div>}</div></>}
      {state.step==='reason'&&<><div className={`direction-mark ${state.direction}`}>{state.direction==='up'?<ArrowUpRight/>:<ArrowDownRight/>}{stock.ticker} · {state.direction==='up'?'ALTA':'QUEDA'}</div><h1>Por que você<br/>acha isso?</h1><p className="lead">Guarde o raciocínio para revisitar depois.</p><Choices label="Motivo" value={state.reason} onChange={reason=>patch({reason})} items={reasonChoices.map(value=>({value,label:value}))}/>{state.reason==='Outro motivo'&&<label className="custom-reason">Seu motivo<textarea maxLength={240} value={state.customReason} onChange={e=>patch({customReason:e.target.value})} placeholder="O que está por trás da sua ideia?"/></label>}<Primary disabled={!reason} onClick={()=>go('terms')}>Continuar</Primary></>}
      {state.step==='terms'&&<><h1>Até quando você<br/>imagina esse movimento?</h1><p className="lead">Estes vencimentos existem nas séries disponíveis para sua ideia.</p><Choices label="Vencimento" className="expiry-choices" value={expiry} onChange={expiry=>patch({expiry,selected:''})} items={expiries.map(value=>({value,label:<><b>{shortDate(value)}</b><small>{daysFrom(stock.sourceDate,value)} dias após o snapshot</small></>}))}/><BottomSheet label={<><Info size={16}/>Por que essas datas?</>} title="Cada opção tem uma data" description="Mostramos apenas vencimentos de séries verificadas que fazem parte desta base. É um recorte educacional, não a lista completa do mercado. As datas não são escolhidas livremente."/><TermStrikeGuide/><OptionGuide/><div className="divider"/><h2>Quanto quer usar<br/>nesta simulação?</h2><Choices label="Valor" className="budget-choices" value={state.budget} onChange={budget=>patch({budget,selected:''})} items={['20','50','100'].map(value=>({value,label:money(Number(value))}))}/><label className="money-input"><span>Outro valor</span><div>R$<input aria-label="Valor da simulação" inputMode="decimal" value={state.budget} maxLength={12} onChange={e=>patch({budget:e.target.value,selected:''})}/></div></label>{!budgetValid&&<p className="field-error" role="alert">Informe um valor positivo de até R$ 1.000.000.</p>}<p className="safety"><LockKeyhole size={16}/>Nenhum dinheiro real será movimentado.</p><Primary disabled={!budgetValid||!expiry} onClick={()=>go('slip',{expiry})}>Revisar meu Pulse</Primary></>}
      {state.step==='slip'&&<><div className="eyebrow">SÍNTESE DA SUA IDEIA</div><h1>Seu Pulse</h1><Slip stock={stock} direction={state.direction} reason={reason} expiry={expiry} budget={budget}/><p className="lead centered">Agora vamos traduzir sua ideia<br/>para uma simulação de opção.</p><Primary disabled={!reason||!budgetValid} onClick={()=>go('option',{lesson:0})}>Continuar</Primary></>}
      {state.step==='option'&&(!option?noOption:<><div className="idea-line">{stock.ticker} · {state.direction==='up'?'alta':'queda'} até {shortDate(expiry)}</div><div className="lesson-count">ENTENDA EM 3 PASSOS · {state.lesson+1}/3</div>{state.lesson===0&&<><h1>Sua visão tem<br/>uma tradução.</h1><div className="option-type"><span>{type}</span><p>{type==='CALL'?'Direito de comprar a ação pelo preço de exercício, conforme as regras do contrato.':'Direito de vender a ação pelo preço de exercício, conforme as regras do contrato.'}</p></div><p className="lead">Você acredita em {state.direction==='up'?'alta':'queda'}. Uma {type} é uma forma de representar essa visão. Acertar a direção, por si só, não garante resultado positivo.</p></>}{state.lesson===1&&<><h1>Um preço definido<br/>no contrato.</h1><div className="translation-card"><span className="mini-label">STRIKE · PREÇO DE EXERCÍCIO</span><div className="big-number">{money(option.strike)}</div><div className="strike-visual"><span>{money(stock.price)}<small>ação no snapshot</small></span><div/><span>{money(option.strike)}<small>strike da opção</small></span></div><p>É o preço pelo qual o direito de {type==='CALL'?'comprar':'vender'} a ação pode ser exercido.</p></div></>}{state.lesson===2&&<><h1>O preço da opção<br/>é o prêmio.</h1><div className="translation-card"><span className="mini-label">PRÊMIO POR UNIDADE</span><div className="big-number">{money(option.premium)}</div><p>{option.premiumType==='illustrative'?'Prêmio ilustrativo, criado somente para demonstração.':`Último negócio registrado em ${date(option.sourceDate)}. Não é cotação atual.`}</p><div className="calculation">{money(option.premium)} × {option.contractSize}<b>{money(cost)}</b></div><p>Posição didática: 100 unidades, cotação por unidade (fator 1). A quantidade é uma hipótese explícita do simulador, não uma especificação de lote validada para operar.</p></div><p className="lead">O orçamento é um limite. Usaremos {money(cost)}; os {money(budget-cost)} restantes não entram na posição.</p></>}
        <OptionGuide/><SeriesNote option={option}/><BottomSheet label="Ver série e outras opções" title="Um critério objetivo" description="Dentro do orçamento, mostramos primeiro a série da base cujo strike está mais próximo do preço da ação no snapshot. O desempate é pelo código. Isso não representa recomendação de investimento."><div className="series-list">{selection.affordable.map(o=><button className={o.ticker===option.ticker?'selected':''} key={o.ticker} onClick={()=>patch({selected:o.ticker})}><b>{o.ticker}</b><span>Strike {money(o.strike)} · custo {money(optionCost(o))}</span><small>{o.premiumType==='illustrative'?'Prêmio ilustrativo':`Prêmio de ${date(o.sourceDate)}`}</small>{o.ticker===option.ticker&&<Check size={16}/>}</button>)}</div><p>Somente séries deste recorte. Outras podem existir no mercado.</p></BottomSheet><Primary onClick={()=>{if(state.lesson===0)learn(type);if(state.lesson===1)learn('STRIKE');if(state.lesson===2){learn('PRÊMIO','VENCIMENTO');go('simulator');}else patch({lesson:state.lesson+1});}}>{state.lesson===2?'Testar cenários':'Entendi, continuar'}</Primary></>)}
      {state.step==='simulator'&&(!option?noOption:<><div className="eyebrow">CENÁRIO HIPOTÉTICO NO VENCIMENTO</div><h1>E se {stock.ticker}<br/>terminar em...</h1><div className="slider-value">{money(state.finalPrice)}</div><Slider value={[state.finalPrice]} min={0} max={Math.ceil(Math.max(stock.price,option.strike,be)*1.5)} step={.01} onValueChange={([finalPrice])=>patch({finalPrice})} aria-label={`Preço final hipotético de ${stock.ticker}`} className="xp-slider"/><div className="slider-labels"><span>R$ 0</span><span>Preço da ação no vencimento</span><span>{money(Math.ceil(Math.max(stock.price,option.strike,be)*1.5))}</span></div><ResultExplanation option={option} price={state.finalPrice}/><div className="scenarios">{[{label:'CAIU',icon:'📉',price:Math.round(Math.min(stock.price*.9,be*.9)*100)/100},{label:'FICOU PRÓXIMO',icon:'➖',price:stock.price},{label:'SUBIU',icon:'📈',price:Math.round(Math.max(stock.price*1.1,be*1.1)*100)/100}].map(s=><button key={s.label} onClick={()=>patch({finalPrice:s.price})}><span>{s.icon} {s.label}</span><b>{money(s.price)}</b><small>{payoff(option,s.price).result>0?'Lucro':payoff(option,s.price).result<0?'Prejuízo':'Equilíbrio'}: {money(Math.abs(payoff(option,s.price).result))}</small></button>)}</div><p className="disclaimer">Cenários escolhidos para explorar a matemática. Não são projeções nem probabilidades.</p><div className="breakeven"><Gauge/><div><span>Ponto de equilíbrio no vencimento</span><b>{stock.ticker} precisa {type==='CALL'?'superar':'ficar abaixo de'} {money(be)} para o resultado ficar positivo.</b></div></div><PriceRanges option={option} price={state.finalPrice} onChange={finalPrice=>patch({finalPrice})}/><TermStrikeGuide/><OptionGuide/><BottomSheet label="Por que esse valor?" title="Primeiro, recuperar o custo" description={type==='CALL'?'A alta precisa cobrir o preço de exercício e também o prêmio pago. No vencimento, o equilíbrio é strike + prêmio por unidade.':'A queda precisa compensar o prêmio pago. No vencimento, o equilíbrio é strike − prêmio por unidade.'} onRead={()=>learn('BREAK-EVEN')}/><p className="safety">Perda máxima da compra isolada neste cálculo: {money(cost)}, além de eventuais custos. O exercício pode gerar uma posição em ações com outros riscos.</p><Primary onClick={()=>{learn('PAYOFF');go('review');}}>Revisar e criar tese</Primary><p className="disclaimer">Cálculo simplificado no vencimento, antes de corretagem, emolumentos, tributos e outros custos. Não precifica venda antecipada da opção.</p><SeriesNote option={option}/></>)}
      {state.step==='review'&&(!option?noOption:<><div className="eyebrow">ANTES DE SALVAR</div><h1>Sua tese,<br/>com tudo às claras.</h1><Slip stock={stock} direction={state.direction} reason={reason} expiry={expiry} budget={budget}/><div className="translation-card"><dl className="result-details"><div><dt>Estratégia</dt><dd>Compra de {type}</dd></div><div><dt>Série</dt><dd>{option.ticker}</dd></div><div><dt>Strike</dt><dd>{money(option.strike)}</dd></div><div><dt>Prêmio por unidade</dt><dd>{money(option.premium)}</dd></div><div><dt>Quantidade didática</dt><dd>{option.contractSize}</dd></div><div><dt>Custo da compra simulada</dt><dd>{money(cost)}</dd></div></dl></div><ResultExplanation option={option} price={state.finalPrice}/><div className="exercise"><Info/><div><b>E no vencimento?</b><p>{type==='CALL'?'Uma CALL exercida pode resultar na compra das ações pelo strike. Isso pode exigir recursos adicionais.':'Uma PUT exercida pode resultar na venda das ações pelo strike. É preciso observar as condições de entrega e as regras da corretora.'} Opções dentro do dinheiro podem ter exercício automático, conforme as regras aplicáveis. O simulador não executa esse processo.</p></div></div><SeriesNote option={option}/><Primary disabled={!reason||!budgetValid} onClick={save}>Criar simulação</Primary></>)}
      {state.step==='created'&&<div className="success-state"><div className="success-icon"><Check/></div><div className="eyebrow">SIMULAÇÃO CRIADA</div><h1>{active?.stock.ticker} · {active?.option.type}</h1><p>Sua tese foi guardada neste navegador. Você pode voltar ao raciocínio e testar o cenário que salvou.</p><div className="unlock"><span>NOVO CONCEITO DISPONÍVEL</span><b>⏳ Tempo</b><p>Uma opção pode mudar de preço mesmo que a ação quase não se mova.</p><TimeLesson days={timeDays} setDays={setTimeDays} onRead={()=>learn('TEMPO')}/></div><Primary onClick={()=>go('pulse')}>Acompanhar</Primary></div>}
      {state.step==='pulse'&&<><div className="eyebrow">MEU PULSE</div><h1>Uma tese para<br/>voltar e entender.</h1>{!state.saved.length?<><p className="lead">Você ainda não criou uma simulação.</p><Primary onClick={()=>go('stock')}>Escolher uma empresa</Primary></>:<>{state.saved.map(s=><article className="thesis-card saved-thesis" key={s.id}><span>{s.stock.ticker} {s.direction==='up'?'↗':'↘'}</span><p>“{s.reason}”</p><dl><div><dt>Criada em</dt><dd>{date(s.createdAt)}</dd></div><div><dt>Vencimento</dt><dd>{date(s.option.expiry)}</dd></div><div><dt>Preço usado na criação</dt><dd>{money(s.stock.price)}</dd></div><div><dt>Snapshot disponível</dt><dd>{money(s.stock.price)} · {date(s.stock.sourceDate)}</dd></div><div><dt>Status</dt><dd>Sem atualização de mercado</dd></div></dl><p className="disclaimer">Base fixa. Não acompanhamos preço ao vivo nem sabemos o resultado futuro desta tese.</p><button className="secondary-button" onClick={()=>go('replay',{activeId:s.id})}><Eye size={18}/>Abrir Pulse Replay</button></article>)}<Primary onClick={()=>go('stock')}>Criar outra tese</Primary></>}</>}
      {state.step==='replay'&&(active?<><div className="eyebrow">PULSE REPLAY · DEMONSTRAÇÃO</div><h1>Direção é só<br/>parte da história.</h1><p className="lead">Este Replay usa o preço hipotético que você salvou. Não relata o que aconteceu no mercado.</p><div className="replay-flow"><span>SUA HIPÓTESE</span><b>{active.reason}</b><i>↓</i><b>{active.stock.ticker} {active.direction==='up'?'subiria':'cairia'}</b><i>↓</i><b>A compra de {active.option.type} poderia ter resultado positivo</b></div><ResultExplanation option={active.option} price={active.finalPrice}/><ReplayResult simulation={active}/><OptionGuide/><div className="replay-card"><span>UMA PERGUNTA PARA FIXAR</span><h2>Acertar a direção garante ganho?</h2><Choices label="Quiz de compreensão" value={quiz} onChange={v=>{setQuiz(v);setQuizFeedback('');}} items={[{value:'yes',label:'Sim, basta acertar alta ou queda.'},{value:'no',label:'Não. Magnitude, prazo e prêmio também importam.'}]}/><Primary disabled={!quiz} onClick={()=>{if(quiz==='no'){patch({quizPassed:true});setQuizFeedback('Isso. O movimento precisa compensar o prêmio dentro do prazo. Você concluiu esta reflexão.');}else setQuizFeedback('Tente novamente: a ação pode subir, mas a alta pode ser insuficiente para recuperar o prêmio da CALL.');}}>Verificar resposta</Primary>{quizFeedback&&<p role="status">{quizFeedback}</p>}{state.quizPassed&&<><strong>30 PULSE CONQUISTADOS</strong><small>Uma única vez por esta compreensão, independentemente do resultado financeiro.</small></>}</div><Primary onClick={()=>go('learned')}>Ver o que aprendi</Primary></>:<><h1>Nenhuma tese selecionada.</h1><Primary onClick={()=>go('pulse')}>Abrir Meu Pulse</Primary></>)}
      {state.step==='learned'&&<><div className="eyebrow">APRENDI</div><h1>Seu progresso<br/>é conhecimento.</h1><div className="score-panel"><span>PULSE SCORE</span><b>{score}</b><p>10 pontos por conceito confirmado + 30 pela reflexão correta. Cada conquista conta uma vez.</p></div><div className="concepts">{Object.keys(definitions).map(name=><div key={name} className={state.concepts.includes(name)?'done':'locked'}>{state.concepts.includes(name)?<Check/>:<LockKeyhole/>}{name==='TEMPO'&&state.saved.length?<TimeLesson days={timeDays} setDays={setTimeDays} onRead={()=>learn('TEMPO')}/>:state.concepts.includes(name)?<BottomSheet label={name} title={name} description={definitions[name]}/>:<span>{name}</span>}</div>)}</div><p className="lead">Novas simulações ajudam a praticar. Repeti-las não aumenta os pontos por si só.</p><Primary onClick={()=>go('stock')}>Explorar uma ideia</Primary></>}
      <footer className="page-footer"><p className="data-note"><Info size={14}/>{topDate}</p><Sources stock={stock}/><p>Protótipo conceitual XP Pulse · sem vínculo operacional com a XP.</p></footer>
    </section>
    {state.saved.length>0&&<nav className="bottom-nav" aria-label="Navegação principal"><button className={state.step==='stock'?'active':''} onClick={()=>go('stock')}>Hoje</button><button onClick={()=>go('stock')}>Explorar</button><button className={['pulse','replay'].includes(state.step)?'active':''} onClick={()=>go('pulse')}>Meu Pulse</button><button className={state.step==='learned'?'active':''} onClick={()=>go('learned')}>Aprendi</button></nav>}
  </div></main>;
}

function Slip({stock,direction,reason,expiry,budget}:{stock:Stock;direction:Direction;reason:string;expiry:string;budget:number}){return <div className="pulse-slip"><div className="slip-head"><div><span>{stock.ticker}</span><b>{stock.name}</b></div><div className={direction}>{direction==='up'?<ArrowUpRight/>:<ArrowDownRight/>}<b>{direction==='up'?'ALTA':'QUEDA'}</b></div></div><dl><div><dt>Motivo</dt><dd>{reason}</dd></div><div><dt>Até</dt><dd>{date(expiry)}</dd></div><div><dt>Orçamento simulado</dt><dd>{money(budget)}</dd></div></dl></div>;}
function SeriesNote({option}:{option:Option}){return <div className="series-note"><b>{option.ticker} · série real verificada</b><p>{option.premiumType==='illustrative'?`Prêmio ilustrativo de ${money(option.premium)} para demonstração em ${date(option.sourceDate)}.`:`Prêmio histórico de ${date(option.sourceDate)}. Valores não atualizados.`} Strike e vencimento consultados em {date(option.specificationDate)}. A posição de 100 unidades é didática; estilo e lote de negociação não foram confirmados.</p><a href={option.sourceUrl} target="_blank" rel="noreferrer">Consultar fonte da série</a></div>;}
function ReplayResult({simulation:s}:{simulation:Simulation}){const p=payoff(s.option,s.finalPrice);const directionRight=s.direction==='up'?s.finalPrice>s.stock.price:s.finalPrice<s.stock.price;return <div className="translation-card"><span className="mini-label">NO CENÁRIO QUE VOCÊ ESCOLHEU</span><dl className="result-details"><div><dt>Fator da sua tese</dt><dd>Não observado nesta base</dd></div><div><dt>{s.stock.ticker} no snapshot</dt><dd>{money(s.stock.price)}</dd></div><div><dt>Preço hipotético em {shortDate(s.option.expiry)}</dt><dd>{money(s.finalPrice)}</dd></div><div><dt>Valor da opção no vencimento</dt><dd>{money(p.value)}</dd></div><div><dt>Resultado após o prêmio</dt><dd className={p.result>=0?'positive':'negative'}>{money(p.result)}</dd></div><div><dt>Direção da hipótese</dt><dd>{directionRight?'✓ compatível':'○ não se confirmou no cenário'}</dd></div><div><dt>Magnitude para cobrir o prêmio</dt><dd>{p.result>0?'✓ suficiente':'○ insuficiente ou no equilíbrio'}</dd></div><div><dt>Prazo</dt><dd>Fixo no vencimento</dd></div></dl><p>Antes do vencimento, o preço da opção também depende de tempo e volatilidade. Este resultado é hipotético.</p></div>;}
function TimeLesson({days,setDays,onRead}:{days:number;setDays:(v:number)=>void;onRead:()=>void}){return <BottomSheet label="Explorar o tempo" title="O tempo também importa" description="Mesmo com a ação parada, o valor temporal pode mudar. Mantidas as outras condições, menos tempo significa menos oportunidade para o movimento ocorrer." onRead={onRead}><label className="time-label">Dias restantes: {days}</label><Slider min={0} max={30} step={1} value={[days]} onValueChange={([v])=>setDays(v)} aria-label="Dias restantes, ilustração conceitual" className="xp-slider"/><p>{days===0?'No vencimento, o valor temporal é zero. Resta o valor intrínseco, se houver.':days<8?'Resta pouco tempo para a ação se mover. A intensidade do efeito varia por contrato.':'Ainda há tempo para diferentes trajetórias da ação. Mais prazo, sozinho, não garante ganho.'}</p><p className="disclaimer">Ilustração qualitativa. Não estima preço, theta ou valorização antes do vencimento.</p></BottomSheet>;}
function Sources({stock}:{stock:Stock}){return <BottomSheet label="Fontes, dados e limites" title="Uma base fixa, com origem clara" description="Este protótipo é um simulador educacional. Preços de ações e alguns prêmios são históricos; os demais prêmios e a quantidade da posição estão identificados como ilustrativos."><ul className="source-links"><li><a href={stock.sourceUrl} target="_blank" rel="noreferrer">{stock.ticker} · snapshot de {date(stock.sourceDate)}</a></li><li><a href="https://www.b3.com.br/pt_br/produtos-e-servicos/negociacao/renda-variavel/opcoes-sobre-acoes.htm" target="_blank" rel="noreferrer">B3 · opções sobre ações e exercício</a></li><li><a href="https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/consultas/mercado-a-vista/opcoes/series-autorizadas/series-autorizadas.htm" target="_blank" rel="noreferrer">B3 · consulta de séries autorizadas</a></li><li><a href="https://conteudo.cvm.gov.br/export/sites/cvm/legislacao/resolucoes/anexos/001/resol030consolid.pdf" target="_blank" rel="noreferrer">CVM 30 · texto consolidado, suitability</a></li><li><a href="https://conteudo.cvm.gov.br/export/sites/cvm/legislacao/resolucoes/anexos/001/resol035consolid.pdf" target="_blank" rel="noreferrer">CVM 35 · texto consolidado, intermediação</a></li></ul><p>Consulta das fontes em 30/09/2026. A base pode ficar antiga e não se atualiza automaticamente. Séries e preços foram consultados nos provedores citados em cada item; não há integração oficial de cotações com a B3.</p><h3>Para operar de verdade</h3><p>Uma futura integração exigiria cadastro, verificação de adequação aos objetivos, situação financeira e conhecimento do cliente, além dos controles aplicáveis. Este simulador não faz aprovação de perfil e não envia ordens.</p></BottomSheet>;}
