import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, ArrowDownRight, ChevronRight } from 'lucide-react';
import stockData from './data/stocks.json';
import optionData from './data/options.json';
import type { Stock, Option } from './types/market';
import { journeyAvailability, safeJourneyStep } from './utils/journey';
import { selectOptions, validOption } from './utils/optionFilters';
import { payoff, optionCost, breakEven } from './utils/optionsMath';
import { money, date } from './utils/format';
import { DirectionAvailability } from './components/DirectionAvailability';
import { BudgetEconomics, BudgetExplorer } from './components/BudgetExplorer';
import { BottomSheet } from './components/BottomSheet';
import { OptionGuide, TermStrikeGuide } from './components/ResultDiscovery';

const stocks=stockData as Stock[], options=(optionData as Option[]).filter(validOption);
const labels=['Empresa','Valor e prazo','Sua visão','Seu motivo','Confirmar','Resultado'];
const key='xp-pulse-simple-v1';
const routes=['stock','terms','context','reason','review','simulator'];
type Draft={version:2;reason:string;customReason:string;step:number;ticker:string;budget:string;expiry:string;direction:'up'|'down'|'';scenario:number};
const initial:Draft={version:2,reason:'',customReason:'',step:0,ticker:stocks[0].ticker,budget:'50',expiry:'',direction:'',scenario:0};
function restore():Draft {
  try {const v=JSON.parse(localStorage.getItem(key)||'null');
    if(!v||!stocks.some(s=>s.ticker===v.ticker)||typeof v.budget!=='string'||typeof v.expiry!=='string'||!['','up','down'].includes(v.direction)||![0,1,2,3,4,5].includes(v.step)||![-10,0,10].includes(v.scenario))return initial;
    return {...v,version:2,step:v.version===2?v.step:v.step>=3?v.step+1:v.step,reason:typeof v.reason==='string'?v.reason:'',customReason:typeof v.customReason==='string'?v.customReason:''};
  }catch{return initial;}
}

export default function SimpleJourney(){
 const [draft,setDraft]=useState<Draft>(restore), [storageError,setStorageError]=useState(false);
 const heading=useRef<HTMLElement>(null);
 const patch=(v:Partial<Draft>)=>setDraft(d=>({...d,...v}));
 const stock=stocks.find(s=>s.ticker===draft.ticker)!;
 const dates=[...new Set(options.filter(o=>o.underlying===stock.ticker).map(o=>o.expiry))].sort();
 const expiry=dates.includes(draft.expiry)?draft.expiry:dates[0]||'';
 const budget=Number(draft.budget.replace(',','.'));
 const validBudget=draft.budget.trim()!==''&&Number.isFinite(budget)&&budget>0&&budget<=1000000;
 const selection=selectOptions(options,stock.ticker,draft.direction==='down'?'PUT':'CALL',expiry,budget,stock.price);
 const option=draft.direction&&validBudget?selection.affordable[0]:undefined;
 const availability=journeyAvailability(options,stock.ticker,validBudget?budget:NaN,expiry);
 const reasonChoices=[...(draft.direction==='up'?stock.bull:stock.bear).map(f=>f.title)];
 const reason=reasonChoices.includes(draft.reason)?draft.reason:'';
 const step=safeJourneyStep(draft.step,availability.canContinue,!!option,!!reason);
 const changeTerms=(changes:Partial<Draft>)=>patch({...changes,step:1,direction:'',reason:'',customReason:''});
 const finalPrice=Math.round(stock.price*(1+draft.scenario/100)*100)/100;
 const result=option?payoff(option,finalPrice):null;
 const go=(step:number,changes:Partial<Draft>={})=>{patch({...changes,step});history.pushState(null,'',`#${routes[step]}`);};
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(draft));setStorageError(false);}catch{setStorageError(true);}},[draft]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});heading.current?.focus({preventScroll:true});history.replaceState(null,'',`#${routes[step]}`);if(draft.step!==step)setDraft(d=>({...d,step}));},[step,draft.step]);
 useEffect(()=>{const back=()=>{const i=routes.indexOf(location.hash.slice(1));if(i>=0)patch({step:i});};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[]);
 const unavailable=<div className="translation-card"><h2>{selection.minimum===null?'Sem opção nesta combinação':'Esse valor não cobre a simulação'}</h2><p>{selection.minimum===null?'A base não tem uma série para esta direção e esta data. Escolha outro prazo ou reveja sua visão.':`A posição didática tem 100 unidades. O menor custo disponível é ${money(selection.minimum)}; seu limite é ${money(budget)}.`}</p><button className="xp-primary" onClick={()=>go(1)}>Ajustar valor ou prazo</button><button className="secondary-button" onClick={()=>go(2)}>Rever alta ou queda</button></div>;
 return <main><div className="ambient"/><div className="app-shell simple-journey">
 <header className="xp-header"><button className="logo logo-home" aria-label="XP Pulse — voltar ao início" onClick={()=>go(0)}><span>XP</span><b>PULSE</b></button><span className="simple-count">{step+1} de 6 · {labels[step]}</span></header>
 <div className="simple-progress" aria-label={`Etapa ${step+1} de 6: ${labels[step]}`}>{labels.map((l,i)=><i key={l} className={i<=step?'filled':''}/>)}</div>
 <div className="simulation-banner">Simulação educacional · nenhum dinheiro real</div>
 <section className="screen" ref={heading} tabIndex={-1} aria-label="Jornada simplificada XP Pulse">
 {step>0&&<button className="simple-back" onClick={()=>go(step-1)}><ArrowLeft size={16}/>Voltar</button>}
 {storageError&&<p role="alert">Não foi possível salvar este rascunho no navegador.</p>}
 {step===0&&<><h1>Qual empresa?</h1><p className="lead">Escolha uma para testar sua ideia.</p><div className="stock-grid">{stocks.map(s=><button className="stock-card" key={s.ticker} onClick={()=>go(1,{ticker:s.ticker,expiry:'',direction:'',scenario:0})}><div><b>{s.name}</b><span>{s.ticker}</span></div><ChevronRight/></button>)}</div><p className="disclaimer">Empresa → valor e prazo → alta ou queda → motivo → confirmação → resultado.</p></>}
 {step===1&&<><div className="eyebrow">{stock.name} · {stock.ticker}</div><h1>Quanto e até quando?</h1><p className="lead">Esse valor é seu limite, não um depósito.</p><label className="money-input"><span>Valor da simulação</span><div>R$<input aria-label="Valor da simulação" inputMode="decimal" maxLength={12} value={draft.budget} onChange={e=>changeTerms({budget:e.target.value})}/></div></label><div className="simple-presets">{[...new Set(['20','50','100',...(availability.minimum===null?[]:[String(availability.minimum)])])].sort((a,b)=>Number(a)-Number(b)).map(b=><button key={b} aria-pressed={draft.budget===b} disabled={availability.minimum===null||Number(b)<availability.minimum} onClick={()=>changeTerms({budget:b})}>{money(Number(b))}</button>)}</div><p className="disclaimer">Mínimo disponível para {stock.ticker}: {availability.minimum===null?'sem séries nesta base':money(availability.minimum)}. Valores menores ficam desabilitados.</p><h2>Prazo</h2><div className="simple-presets">{availability.dates.map(d=><button key={d.date} aria-pressed={expiry===d.date} disabled={!d.enabled} onClick={()=>changeTerms({expiry:d.date})}>{date(d.date)}<small>A partir de {money(d.minimum!)}</small></button>)}</div><p className="disclaimer">Cada opção tem um preço: prêmio por unidade × 100 unidades didáticas. Se o custo passa do seu limite, ela não cabe. Um prazo fica desabilitado quando nenhuma opção dessa data cabe no valor.</p><BudgetEconomics/><BudgetExplorer key={`${stock.ticker}-${budget}-${expiry}`} stock={stock} options={options} budget={budget} expiry={expiry} onApply={(value,term)=>changeTerms({budget:String(value),expiry:term})}/>{!validBudget&&<p className="field-error" role="alert">Digite um valor maior que zero e até R$ 1.000.000.</p>}{validBudget&&!availability.canContinue&&<p className="field-error" role="status">{availability.minimum!==null&&budget<availability.minimum?`Use pelo menos ${money(availability.minimum)} para continuar.`:'Escolha um prazo habilitado ou ajuste o valor.'}</p>}<button className="xp-primary" disabled={!availability.canContinue} onClick={()=>go(2,{expiry})}>Ver o que pode acontecer</button></>}
 {step===2&&<><div className="eyebrow">{stock.name}</div><h1>Você acha que sobe ou cai?</h1><p className="lead">Veja o que pode influenciar. São possibilidades, não previsões.</p><div className="simple-factors">{(['up','down'] as const).map(tone=><div key={tone}><h2>{tone==='up'?<ArrowUpRight/>:<ArrowDownRight/>}{tone==='up'?'Pode subir se…':'Pode cair se…'}</h2>{(tone==='up'?stock.bull:stock.bear).slice(0,3).map(f=><div className="economic-factor" key={f.title}><b>{f.title}</b><p>{f.short}</p><BottomSheet label={`Entender: ${f.title}`} title={f.title} description={f.detail}><h3>Por que a ação poderia reagir?</h3><p>Investidores reavaliam quanto a empresa pode ganhar no futuro. Se a nova informação mudar essa expectativa, o preço que aceitam pagar pela ação também pode mudar.</p><h3>O que pode mudar essa leitura?</h3><p>O mercado pode já ter antecipado esse cenário. Outros fatores podem compensá-lo. Uma notícia boa não garante alta, nem uma notícia ruim garante queda.</p><p className="disclaimer">Mecanismo econômico ilustrativo, não notícia atual ou previsão. O simulador não transforma este fator em uma porcentagem de alta ou queda.</p></BottomSheet></div>)}</div>)}</div><div className="direction-grid">{availability.directions.map(d=><button key={d.direction} disabled={!d.enabled} aria-describedby={!d.enabled?`unavailable-${d.direction}`:undefined} aria-pressed={draft.direction===d.direction} onClick={()=>patch({direction:d.direction,reason:'',customReason:''})}>{d.direction==='up'?<ArrowUpRight/>:<ArrowDownRight/>}<span><b>{d.direction==='up'?'Acho que sobe':'Acho que cai'}</b><small>{d.minimum===null?'Sem série neste prazo':d.enabled?'Disponível':`Precisa de ${money(d.minimum)}`}</small></span></button>)}</div>{availability.directions.filter(d=>!d.enabled).map(d=><DirectionAvailability key={d.direction} direction={d.direction} minimum={d.minimum} expiry={expiry} budget={budget} ticker={stock.ticker} options={options} onAdjust={()=>go(1)} onDate={newExpiry=>patch({expiry:newExpiry,direction:'',reason:'',customReason:''})}/>)}<p className="disclaimer">Escolha a direção que faz mais sentido para você com base nos fatores acima.</p><button className="xp-primary" disabled={!option} onClick={()=>go(3)}>Continuar</button></>}
 {step===3&&<><div className="eyebrow">{stock.name} · {draft.direction==='up'?'ALTA':'QUEDA'}</div><h1>Por que você acha que vai {draft.direction==='up'?'subir':'cair'}?</h1><p className="lead">Guarde o motivo da sua escolha.</p><fieldset className="reason-options"><legend>Seu motivo</legend>{reasonChoices.map(r=><label key={r}><input type="radio" name="reason" checked={draft.reason===r} onChange={()=>patch({reason:r})}/><span>{r}</span></label>)}</fieldset><button className="xp-primary" disabled={!reason||!option} onClick={()=>go(4)}>Revisar minha escolha</button></>}
 {step===4&&<><h1>Está tudo certo?</h1>{!option?unavailable:<><div className="pulse-slip"><div className="slip-head"><div><span>{stock.name}</span><b>{stock.ticker}</b></div><b>{draft.direction==='up'?'↑ Alta':'↓ Queda'}</b></div><dl><div><dt>Motivo</dt><dd>{reason}</dd></div><div><dt>Seu limite</dt><dd>{money(budget)}</dd></div><div><dt>Valor usado</dt><dd>{money(optionCost(option))}</dd></div><div><dt>Não utilizado</dt><dd>{money(budget-optionCost(option))}</dd></div><div><dt>Até</dt><dd>{date(expiry)}</dd></div></dl></div><p className="lead">Você pode perder todo o valor usado: <b>{money(optionCost(option))}</b>, antes de custos.</p><p className="disclaimer">{option.premiumType==='illustrative'?'O preço da opção é ilustrativo.':'O preço da opção é histórico.'} O resultado será um cenário, não uma previsão.</p><button className="xp-primary" disabled={!option||!reason} onClick={()=>go(5,{scenario:0})}>Confirmar e ver resultado</button><details className="simple-details"><summary>Qual opção será simulada?</summary><Contract option={option}/><p>Escolhemos, entre as séries que cabem no limite, o strike mais próximo da ação no snapshot. Não é recomendação.</p><OptionGuide/></details></>}</>}
 {step===5&&<>{!option||!result?unavailable:<><div className="eyebrow">{stock.name} · {date(expiry)}</div><h1>Seu resultado simulado</h1><p className="lead">E se a ação terminasse assim?</p><div className="simple-presets scenario-picker" aria-label="Cenário hipotético">{[-10,0,10].map(n=><button key={n} aria-pressed={draft.scenario===n} onClick={()=>patch({scenario:n})}>{n===0?'Mesmo preço':n<0?'Cai 10%':'Sobe 10%'}</button>)}</div><p className="simple-price">Ação: {money(stock.price)} → <b>{money(finalPrice)}</b></p><div className={`result-card ${result.result>0?'gain':result.result<0?'loss':'neutral'}`} role="status" aria-live="polite" aria-atomic="true"><span>NESTE CENÁRIO, VOCÊ TERIA</span><h2>{result.result>0?'Lucro':result.result<0?'Prejuízo':'Zero a zero'}</h2><b>{money(Math.abs(result.result))}</b><p>{result.result===0?'Recuperaria o valor usado, sem lucro.':'Já descontado o valor usado na opção.'}</p></div><div className="simple-why"><h2>Por quê?</h2><p>{result.value===0?`A ação não terminou ${option.type==='CALL'?'acima':'abaixo'} de ${money(option.strike)}. A opção não teria valor no vencimento, e você perderia os ${money(result.cost)} usados.`:result.result<0?`A opção valeria ${money(result.value)}, mas custou ${money(result.cost)}. A diferença de ${money(-result.result)} seria sua perda.`:result.result>0?`A opção valeria ${money(result.value)}. Tirando os ${money(result.cost)} que você usou, sobrariam ${money(result.result)} de lucro.`:`A opção valeria ${money(result.value)}, exatamente o que você pagou. Não haveria ganho nem perda antes de custos.`}</p></div><p className="disclaimer">Hipótese, não resultado real. Antes de taxas e tributos; não calcula venda antecipada.</p><button className="xp-primary" onClick={()=>go(0,{direction:'',scenario:0})}>Simular outra empresa</button><details className="simple-details"><summary>Entender melhor a conta e os conceitos</summary><p>Para lucrar no vencimento, a ação precisa ficar {option.type==='CALL'?'acima':'abaixo'} de <b>{money(breakEven(option))}</b>. Acertar alta ou queda não basta.</p><p>Valor no vencimento {money(result.value)} − custo {money(result.cost)} = resultado {money(result.result)}. Os {money(budget-result.cost)} não utilizados ficam fora da conta.</p><Contract option={option}/><p>Não há crédito de dinheiro nem exercício neste protótipo. O exercício real pode envolver ações, entrega e recursos adicionais.</p><OptionGuide/><TermStrikeGuide/></details></>}</>}
 <footer className="page-footer"><details><summary>Dados e limites da simulação</summary><p>Base fixa: ação de {date(stock.sourceDate)}, não atualizada em tempo real. Preços finais de −10%, 0% e +10% são hipóteses didáticas, não probabilidades. Os fatores não comprovam a causa de um movimento de preço.</p><a href={stock.sourceUrl} target="_blank" rel="noreferrer">Fonte do preço de {stock.ticker}</a><p>Protótipo conceitual, sem vínculo operacional com a XP. Não envia ordens nem recomenda investimentos.</p></details></footer>
 </section></div></main>;
}
function Contract({option:o}:{option:Option}){return <><p>{o.ticker} · {o.type} · strike {money(o.strike)} · vencimento {date(o.expiry)}.</p><p>{o.contractSize} unidades didáticas × {money(o.premium/o.quoteFactor)} por unidade = {money(optionCost(o))}. Quantidade ilustrativa; lote e estilo de exercício não confirmados.</p><p>Prêmio {o.premiumType==='illustrative'?'ilustrativo':'histórico'} de {date(o.sourceDate)}. <a href={o.sourceUrl} target="_blank" rel="noreferrer">Consultar fonte</a>.</p></>}
